# Generated by Django 2.0.6 on 2018-06-19 20:19

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResourceArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=50)),
                ('date_uploaded', models.DateField(default=datetime.date.today, verbose_name='date uploaded')),
                ('file_upload', models.FileField(upload_to='')),
                ('file_url', models.URLField()),
                ('tags', models.CharField(max_length=50)),
                ('part_of_city', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='end date')),
                ('media_sources', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MapItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=1000)),
                ('info_sources', models.CharField(max_length=1000)),
                ('location_notes', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='end date')),
                ('status', models.CharField(max_length=50)),
                ('location1', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('location2', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('tags', models.CharField(max_length=50)),
                ('media_embeds', models.URLField(max_length=400)),
                ('min_zoom', models.IntegerField()),
                ('max_zoom', models.IntegerField()),
                ('overlay_group', models.IntegerField()),
                ('themes', models.CharField(max_length=50)),
                ('structure_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OralHistories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('info_sources', models.CharField(max_length=200)),
                ('location_notes', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='end date')),
                ('oral_history_status', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('media', models.CharField(max_length=200)),
                ('media_embeds', models.URLField()),
                ('min_zoom', models.IntegerField()),
                ('max_zoom', models.IntegerField()),
                ('overlay_group', models.IntegerField()),
                ('themes', models.CharField(max_length=50)),
                ('structure_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('credits', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('file_upload', models.FileField(upload_to='')),
                ('file_url', models.URLField()),
                ('tags', models.CharField(max_length=50)),
                ('part_of_city', models.CharField(max_length=50)),
                ('time_period', models.CharField(max_length=50)),
                ('map_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsite.MapItems')),
            ],
        ),
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('file_upload', models.FileField(upload_to='')),
                ('file_url', models.URLField()),
                ('tags', models.CharField(max_length=50)),
                ('part_of_city', models.CharField(max_length=50)),
                ('time_period', models.CharField(max_length=50)),
                ('credits', models.CharField(max_length=50)),
                ('map_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsite.MapItems')),
            ],
        ),
        migrations.AddField(
            model_name='digitalresourcearchive',
            name='map_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsite.MapItems'),
        ),
    ]
