# Generated by Django 2.0.6 on 2018-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapitems',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapitems',
            name='media',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapitems',
            name='summary',
            field=models.CharField(max_length=300),
        ),
    ]
