# Generated by Django 2.0.6 on 2018-06-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'media'},
        ),
    ]
