# Generated by Django 2.0.6 on 2018-07-24 19:01

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'media'},
        ),
        migrations.AlterModelOptions(
            name='taggroup',
            options={'verbose_name': 'Tag Group', 'verbose_name_plural': 'Tag Groups'},
        ),
        migrations.AlterModelOptions(
            name='webseries',
            options={'verbose_name': 'Episode', 'verbose_name_plural': 'Web Series'},
        ),
        migrations.AddField(
            model_name='webseries',
            name='file_iframe',
            field=models.CharField(blank=True, help_text='Please paste in an &lt;iframe&gt; to embed external content. Content must begin with &lt;iframe&gt; and end with &lt;/iframe&gt; ', max_length=1000, null=True, verbose_name='File <iframe>'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='info_sources',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='location1',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='location2',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='location_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='max_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='media',
            field=models.ManyToManyField(blank=True, through='dpsite.MappedMedia', to='dpsite.Media'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='min_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='overlay_group',
            field=models.ManyToManyField(blank=True, to='dpsite.OverlayGroup'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dpsite.Tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='credits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_sources',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='media',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dpsite.Tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpsite.TagGroup'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='credits',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='File URL'),
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='map_location',
        ),
        migrations.AddField(
            model_name='webseries',
            name='map_location',
            field=models.ManyToManyField(blank=True, to='dpsite.MapItem'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dpsite.Tag'),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Uploaded'),
        ),
    ]
