# Generated by Django 2.0.6 on 2018-07-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0002_auto_20180724_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webseries',
            options={'ordering': ['season', 'episode'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Web Series'},
        ),
    ]
