# Generated by Django 2.0.6 on 2018-06-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0002_auto_20180628_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_iframe',
            field=models.CharField(blank=True, help_text='Please paste in an <iframe> to embed external content. Content must begin with <iframe> and end with </iframe>', max_length=1000, verbose_name='File <iframe>'),
        ),
        migrations.AlterField(
            model_name='media',
            name='credits',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_sources',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='media',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dpsite.Tag'),
        ),
    ]
