# Generated by Django 2.0.6 on 2018-06-19 21:00

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0002_auto_20180619_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('info_sources', models.CharField(max_length=1000)),
                ('location_notes', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='end date')),
                ('status', models.CharField(max_length=50)),
                ('location1', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('location2', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('tags', models.CharField(max_length=50)),
                ('media', models.FileField(upload_to='')),
                ('min_zoom', models.IntegerField()),
                ('max_zoom', models.IntegerField()),
                ('overlay_group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('credits', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('file_upload', models.FileField(upload_to='')),
                ('file_url', models.URLField()),
                ('tags', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='end date')),
                ('media_sources', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='digitalresourcearchive',
            name='map_location',
        ),
        migrations.DeleteModel(
            name='OralHistories',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='map_location',
        ),
        migrations.AlterField(
            model_name='webseries',
            name='map_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpsite.MapItem'),
        ),
        migrations.DeleteModel(
            name='DigitalResourceArchive',
        ),
        migrations.DeleteModel(
            name='MapItems',
        ),
        migrations.DeleteModel(
            name='VideoGallery',
        ),
    ]
