# Generated by Django 2.0.6 on 2018-06-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0003_auto_20180628_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_iframe',
            field=models.CharField(blank=True, help_text='Please paste in an &lt;iframe&gt; to embed external content. Content must begin with &lt;iframe&gt; and end with &lt;/iframe&gt;', max_length=1000, verbose_name='File <iframe>'),
        ),
    ]
