# Generated by Django 2.0.6 on 2018-06-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0004_auto_20180620_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mapitem',
            name='summary',
        ),
    ]
