# Generated by Django 2.0.6 on 2018-06-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0005_auto_20180629_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggroup',
            options={'verbose_name': 'Tag Group', 'verbose_name_plural': 'Tag Groups'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dpsite.TagGroup'),
        ),
    ]
