# Generated by Django 2.0.6 on 2018-07-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0006_remove_webseries_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='webseries',
            name='map_location',
            field=models.ManyToManyField(blank=True, to='dpsite.MapItem', verbose_name='Map'),
        ),
    ]
