# Generated by Django 2.0.6 on 2018-07-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0007_webseries_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='webseries',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='If you are uploading a non-image file or using the File URL or File IFrame options, its recommended you select a thumbnail. If you do not, a default image will be used.', null=True, upload_to='', verbose_name='File Upload'),
        ),
    ]
