# Generated by Django 2.0.6 on 2018-06-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0007_auto_20180629_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_sources',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sources'),
        ),
    ]
