# Generated by Django 2.0.6 on 2018-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0008_webseries_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hook', models.CharField(max_length=50, verbose_name='Text Hook')),
                ('page_text', models.TextField(verbose_name='Page Text')),
            ],
            options={
                'verbose_name_plural': 'Page Text',
                'verbose_name': 'Page Text',
                'ordering': ['text_hook'],
            },
        ),
        migrations.AlterField(
            model_name='webseries',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='If you are uploading a non-image file or using the File URL or File IFrame options, its recommended you select a thumbnail. If you do not, a default image will be used.', null=True, upload_to='', verbose_name='Thumbnail'),
        ),
    ]
