# Generated by Django 2.0.6 on 2018-06-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0008_auto_20180629_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
