# Generated by Django 2.0.6 on 2018-07-26 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0009_auto_20180726_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['title'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='If you are uploading a non-image file or using the File URL or File IFrame options, its recommended you select a thumbnail. If you do not, a default image will be used.', null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Uploaded'),
        ),
    ]
