# Generated by Django 2.0.6 on 2018-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0009_auto_20180629_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='credits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
