# Generated by Django 2.0.6 on 2018-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0010_auto_20180629_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_iframe',
            field=models.CharField(blank=True, help_text='Please paste in an &lt;iframe&gt; to embed external content. Content must begin with &lt;iframe&gt; and end with &lt;/iframe&gt;', max_length=1000, null=True, verbose_name='File <iframe>'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_sources',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='dpsite.Tag'),
        ),
    ]
