# Generated by Django 2.0.6 on 2018-06-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0011_auto_20180629_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dpsite.Tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
