# Generated by Django 2.0.6 on 2018-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0013_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitem',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
