# Generated by Django 2.0.6 on 2018-07-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0013_auto_20180726_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappedmedia',
            options={'ordering': ('order',), 'verbose_name': 'File', 'verbose_name_plural': 'Media'},
        ),
    ]
