# Generated by Django 2.0.6 on 2018-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0014_auto_20180727_2019'),
    ]

    operations = [
    ]
