# Generated by Django 2.0.6 on 2018-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0014_auto_20180702_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitem',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
