# Generated by Django 2.0.6 on 2018-07-02 19:42

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0015_auto_20180702_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapitem',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='info_sources',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='location1',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='location2',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='location_notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='max_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='min_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mapitem',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
