# Generated by Django 2.0.6 on 2018-08-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0015_auto_20180801_1518'),
        ('dpsite', '0014_auto_20180727_1956'),
        ('dpsite', '0014_auto_20180807_1551'),
    ]

    operations = [
    ]
