# Generated by Django 2.0.6 on 2018-07-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0014_auto_20180702_1606'),
        ('dpsite', '0014_auto_20180702_1559'),
        ('dpsite', '0014_auto_20180702_1600'),
        ('dpsite', '0016_auto_20180702_1942'),
    ]

    operations = [
    ]
