# Generated by Django 2.0.6 on 2018-08-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0017_auto_20180815_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetext',
            name='related_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Related Image'),
        ),
    ]
