# Generated by Django 2.0.6 on 2018-12-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('dpsite', '0018_auto_20180815_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=50)),
                ('slide_text', models.TextField(verbose_name='Slide Text')),
                ('related_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Related Image')),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Home Slide',
                'ordering': ['order'],
                'verbose_name_plural': 'Home Slides',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('site_title', models.CharField(max_length=50, verbose_name='Site Title')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.Site')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Favicon')),
                ('home_sidebar', models.TextField(blank=True, null=True, verbose_name='Home Sidebar')),
                ('aboutproject_main_text', models.TextField(blank=True, null=True, verbose_name='About Project Main Text')),
                ('aboutproject_main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='About Project Main Image')),
                ('aboutproject_sidebar_text', models.TextField(blank=True, null=True, verbose_name='About Project Sidebar Text')),
                ('aboutproject_sidebar_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='About Project Sidebar Image')),
                ('aboutproject_smsidebar_text', models.TextField(blank=True, null=True, verbose_name='About Project Mini-Sidebar Text')),
                ('aboutteam_main_text', models.TextField(blank=True, null=True, verbose_name='About Team Main Text')),
                ('aboutteam_main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='About Team Main Image')),
                ('aboutteam_sidebar_text', models.TextField(blank=True, null=True, verbose_name='About Team Sidebar Text')),
                ('aboutteam_sidebar_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='About Team Sidebar Image')),
                ('aboutteam_smsidebar_text', models.TextField(blank=True, null=True, verbose_name='About Team Mini-Sidebar Text')),
                ('webseries_sidebar', models.TextField(blank=True, null=True, verbose_name='Web Series Sidebar')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'ordering': ['site_title'],
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.DeleteModel(
            name='PageText',
        ),
    ]
