# Generated by Django 2.0.6 on 2018-12-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0019_auto_20181207_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer',
            field=models.TextField(blank=True, null=True, verbose_name='Footer'),
        ),
    ]
