# Generated by Django 2.0.6 on 2018-12-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0020_auto_20181210_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='map_sidebar',
            field=models.TextField(blank=True, null=True, verbose_name='Map Sidebar'),
        ),
    ]
