# Generated by Django 2.2.5 on 2019-09-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsite', '0023_auto_20190919_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
